version: '3'

services:
  app:
    build: .
    entrypoint: ./.docker/entrypoint.sh
    container_name: nestjs_template
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - /data/postgres:/data/postgres
    env_file:
    - .docker/docker.env
    networks:
    - postgres
  
  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
    - "8080:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    env_file:
    - .docker/docker.env
    networks:
    - postgres
  
networks:
  postgres:
    driver: bridge