version: '3'

services:
  postgres-database:
    image: postgres:10.15-alpine
    volumes:
      - /Docker/database:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata 
      POSTGRES_DB: nest
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: P@ssw0rd
  api-nest:
    build:  
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 5000:5000
    restart: always
    volumes:
      - ./:/app
    environment:
      PORT: 5000
    depends_on: 
      - postgres-database
    
