openapi: 3.0.0
info: 
  title: AutoBetter API
  version: 0.0.1
paths: 
  /bet/: 
    get: 
      responses: 
        '200':
          description: Latest bet
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/bet' 
    post: 
      requestBody:
        description: Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bet'
      responses: 
        '200':
          description: Latest bet
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/bet' 
  /bet/latest: 
    get: 
      responses: 
        '200':
          description: Latest bet which is between odds 1-10 and ev is over 5
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/bet' 
  /bet/{id}: 
    patch: 
      parameters: 
      - name: id
        in: path
        required: true
        schema: 
          $ref: '#/components/schemas/date'
      requestBody:
        description: Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bet'
      responses: 
        '200':
          description: Update the odds and ev of bet
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/bet'
components:
  schemas: 
    date: 
      type: string
      format: datetime
    bet:
      type: object
      properties:
        id:
          type: integer
        date:
          $ref: '#/components/schemas/date'
        course_name:
          type: string
        number:
          type: integer
        url:
          type: string
          format: url
        odds:
          type: integer
        ev:
          type: number
        placed:
          type: boolean
        