openapi: 3.0.0
info: 
  title: AutoBetter API
  version: 0.0.1
paths: 
  /schedule/{date}: 
    get: 
      parameters: 
      - name: date
        in: path
        required: true
        schema: 
          $ref: '#/components/schemas/date'
      responses: 
        '200':
          description: Schedule
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/schedule' 
    post: 
      parameters: 
      - name: date
        in: path
        required: true
        schema: 
          $ref: '#/components/schemas/date'
      requestBody:
        description: Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/race'
      responses: 
        '200':
          description: Added race to schedule
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/race'
  /bet/{date}: 
    get: 
      parameters: 
      - name: date
        in: path
        required: true
        schema: 
          $ref: '#/components/schemas/date'
      responses: 
        '200':
          description: Latest bet
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/bet' 
    post: 
      parameters: 
      - name: date
        in: path
        required: true
        schema: 
          $ref: '#/components/schemas/date'
      requestBody:
        description: Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/bet'
      responses: 
        '200':
          description: Latest bet
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/bet' 
components:
  schemas: 
    date: 
      type: string
      format: datetime
    race:
      type: object
      properties:
        id:
          type: integer
        date:
          $ref: '#/components/schemas/date'
        course_name:
          type: string
        number:
          type: integer
        url:
          type: string
          format: url
    bet: 
      type: object
      properties: 
        id:
          type: integer
        date:
          $ref: '#/components/schemas/date'
        odds:
          type: integer
        ev:
          type: number
        race:
          $ref: '#/components/schemas/race'
    schedule:
        type: array
        items:
          $ref: '#/components/schemas/race'
        